//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub mod article;
pub mod calendar;
pub mod chart;
pub mod chart_tag;
pub mod chat;
pub mod comment;
pub mod config;
pub mod institute;
pub mod ip;
pub mod leaderboard_snapshot;
pub mod media;
pub mod notification;
pub mod oauth;
pub mod oauth_provider;
pub mod registration;
pub mod result;
pub mod result_review;
pub mod scoring_script_version;
pub mod team_member;
pub mod tournament;
pub mod tournament_round;
pub mod tournament_staff;
pub mod tournament_team;
pub mod user;
pub mod user2_ip;
