platform:
  exposure:
    type: ingress
  ingress:
    className: nginx
    hosts:
      - host: rhythm.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ret2shell-tls
        hosts:
          - rhythm.example.com
  config:
    server:
      externalDomain: rhythm.example.com
